Fix: CVE-2024-42471
Resourcely-Inc/scaffolding-github-actions pull request #10
Opened 2024-09-03 23:58 UTC by alaamub

# what 
Versions of actions/download-artifact before 4.1.7 are vulnerable to arbitrary file write when downloading and extracting a specifically crafted artifact that contains path traversal filenames.

2024-09-04 14:30 UTC, drbild requested changes

2024-09-04 14:30 UTC, drbild commented on .github/workflows/terraform.yml
> +        uses: actions/download-artifact@4.1.7
Missing the `v` prefix.  And might as well update to the latest version, while we're at it:

```
actions/download-artifact@v4.1.8
```

2024-09-04 14:30 UTC, drbild commented on .github/workflows/terraform.yml
> +        uses: actions/download-artifact@4.1.7
Ditto.

2024-09-04 15:45 UTC, alaamub commented on .github/workflows/terraform.yml
> +        uses: actions/download-artifact@4.1.7
nice catch, fixed

2024-09-04 15:45 UTC, alaamub commented on .github/workflows/terraform.yml
> +        uses: actions/download-artifact@4.1.7
nice catch, fixed

2024-09-04 16:04 UTC, drbild commented on .github/workflows/terraform.yml
> +        uses: actions/download-artifact@v4.1.7
Missed this before.  Need to upgrade `actions/upload-artifact` on line 56 to `v4.4.0`.

2024-09-06 16:28 UTC, drbild approved these changes

2024-09-06 16:29 UTC, merged